name: AirPortal
author: Sorroko
main: me.sorroko.vortex.AirPortal
version: 0.0.2
description: Teleport in style with an airportal.
commands:
  airportal:
    usage: /airportal
    description: Base command
    aliases: [portal, ap]
permissions:
    airportal.*:
        description: Allows you to use everything
        default: op
    airportal.use:
        description: Allows you to use portals
        default: true
    airportal.admin:
        description: Allows you to use all the commands
        default: op